### ISSUE TITLE
FutureWarning in skgof

### ISSUE THREAD

**Issue by enourbakhsh** [LSSTDESC/pz_blend#11]
The `skgof` [module](https://github.com/wrwrwr/scikit-gof) is not maintained anymore. `import skgof` gives: 

> /usr/local/anaconda3/lib/python3.7/site-packages/skgof/ecdfgof.py:45: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
>   from .cvmdist import cvm_unif

**Comment by ih64** [comment]
we might be better off just getting rid of it. We can do KS test by hand analytically or use scipy, and not worry about the anderson darling test and cramer von mises test. @sschmidt23 pointed out that they tracked KS test pretty closely in the DC1 paper, and might be redundant here

**Comment by enourbakhsh** [comment]
I fixed it in my fork of `scikit-gof`. You can install it by:

pip git+https://github.com/cosmicshear/scikit-gof

**Comment by enourbakhsh** [comment]
Fixed in [this](https://github.com/LSSTDESC/pz_blend/commit/2cbcd06aa214acfd1808624a78a77e41e6228e63) commit.
